module.exports={
    EVENT_COLLECTION:'event',
    REGISTEREVENT_COLLECTION:'registered',
    USER_COLLECTION:'user',
    JUDGE_COLLECTION:'judge',
    ITEM_COLLECTION:'item',
    ADMIN_COLLECTION:'admin',
    EVENT_TIME_LOG:'eventlogs',
}